version: "3"

services:
  master:
    build: .
    image: locust
    volumes:
      - ./locustfile.py:/locust/locustfile.py
    ports:
      - "8089:8089"
    command:
      - "locust"
      - "--host=${APP_HOST}"
      - "--master"

  slave:
    build: .
    image: locust
    volumes:
      - ./locustfile.py:/locust/locustfile.py
    command: "locust --master-host=master --slave"
